mgechev/angular-seed

app/app.ts
app/components/about/about.ts
app/components/home/home.ts
app/init.ts
tsconfig.json

As all typings are well referenced in the `tsconfig.js` file, references in each `*.ts` files is useless.

style: remove unnecessary typings ref

---

app/typings/_custom.d.ts
tsd.json
tsd_typings/systemjs/systemjs.d.ts
tsd_typings/tsd.d.ts

We can now use systemjs.d.ts from definitelytyped and can remove the customization since it's no longer needed.
https://github.com/mgechev/angular2-seed/issues/47

chore: we can now use systemjs.d.ts from definitelytyped

---

app/app.ts
app/init.ts
package.json

There's a workaround with System.js in order to make it work. It shouldn't be necessary when alpha35 is relased.

Update to angular2-alpha34

---

gulpfile.js

path.join() was being used to concatenate a gulp excluding `'!'` with a path, resulting in the PATH.dest.dev.lib folder being deleted when serving dev.
This fix removes the wrong path.join() in favor of simple string concatenation.

Fixed wrong use of path.join() in gulpfile clean.app.dev task

---

package.json
tsconfig.json

I upgraded Typescript to 1.6.0, gulp-typescript to 2.8.2, system.js to 0.18.17 and app seems to run fine despite one error during 'gulp serve.dev': app/init.ts(1,1): error TS2304: Cannot find name 'System'.

configuration for typescript 1.6.0

---

gulpfile.js
package.json

1. On windows, there's problem with require.resolve, which resolve to path with `\`. Gulp is not able to split it by `/`, and therefore unable to inject lib scripts.

Problem with slashes after using require.resolve

---

gulpfile.js
package.json

Two fixes:
- `require.resolve` cant find module `traceur` when npm 3.3.3 is used
- move from `tiny-lr` to `mini-lr`

fix(build): make it compatible with npm3

---

tools/workflow.config.js

system-polyfills.js might be included by some browsers (i.e. IE) and SystemJS tries to load it from lib/ directory.

Add system-polyfills file to the lib/ dist directory

---

karma.conf.js
package.json
tools/workflow.config.ts

Seems like everything works fine after the upgrade.
All references to `es6-module-loader-sans-promises.js` renamed to `es6-module-loader.js`.

es6-module-loader, systemjs dependencies bump

---

test-main.js
tools/tasks/build.js.dev.ts

Many people use Xyz.spec.js for their test files - with this change
we support both, *.spec.js and *_spec.js.

Allow .spec.js and _spec.js files for writing tests

---

tools/utils/tasks-tools.ts

IntelliJ transpiles to the local directory, which causes restarts on the gulp build to fail. This fixes the problem.

Fix for IntelliJ

---

README.md
package.json

This addresses issue #158, but only when you are in trouble.
This approach has a tradeoff: Firstly it is not done automatically, which requires the use to think after being in trouble
On the other hand, this approach saves time since a full clearing of caches and installation of all modules takes time.
Furthermore, adding the command as "npm run reinstall" makes it explicit what should and could be done

If npm install fails, use "npm run reinstall" to ensure we start at clean slate

---

circle.yml
karma.conf.js

It could add value to users of the seed project, that they can easily setup build on CircleCI
**A note on Headless PhantomJS**: Making the build to run headless PhantomJS2 is not working for me (but is also a topic for a separate issue/PR)
In case you are interested, here is the passing CircleCI build for the fix 
https://circleci.com/gh/jesperronn/angular2-seed/9

Circleci test setup

---

app/components/app/app_spec.ts

Moving beforeEachProviders() from global scope, where it only makes sense to have one, to inside the describe. Then other tests can have their own beforeEachProviders() inside their describes and Jasmine will take care of cleaning up the installed providers after the describe has been run.

fixing issue that prevents more than one test using Router

---

tools/utils/template-injectables.ts

Hello,
I get wrong paths on windows & firefox (chrome doesn't care) because the index.html tries to load files with backslashes instead of regular slashes.
Looking at the gulpfiles, the problem is here: https://github.com/mgechev/angular2-seed/blob/master/tools/utils/template-injectables.ts#L22
This returns:
```html
<script src="\node_modules\zone.js\dist\zone.js"></script>
<script src="\node_modules\es6-shim\es6-shim.min.js"></script>
<script src="\node_modules\reflect-metadata\Reflect.js"></script>
<script src="\node_modules\systemjs\dist\system.src.js"></script>
```
when it should return:
```html
<script src="/node_modules/zone.js/dist/zone.js"></script>
<script src="/node_modules/es6-shim/es6-shim.min.js"></script>
<script src="/node_modules/reflect-metadata/Reflect.js"></script> …
```

Fix paths for windows

---

package.json
tools/tasks/check.versions.ts
tools/utils/tasks-tools.ts

Two changes:
- Made the code in `walk` compatible with older versions of node (in order to allow the user to see the error message).
- Add chalk for cleaner error message that the current node or npm version is not supported.

Add fancier error message when npm or node are not required version

---

gulpfile.ts
tools/utils/tasks_tools.ts

* Improve build start by just loading the required tasks.
* Single tasks like `check.versions` now needs to be explicitly declared in gulpfile (as not all the tasks file are loaded on start).

Load only necessary task files

---

gulpfile.ts
tools/utils/tasks_tools.ts

According to pull request 312, ludohenin created a "new" runSequence method for group tasks in order to load the proper files before we run the task.
I think its unnecessary, and it is better to load everything, but just using a cb.
When the task runs every subtask will load itself.. gulp invoking the cb => we require the file..
it is also not possible to run specific tasks right now like: gulp build.index, and "clean" tasks also pre-loaded, this change will fix that.

Lazy load gulp tasks

---

README.md

There is no `config.js` available. Fixed readme to refer to `config.ts`

fixed readme to refer to config.ts

---

package.json
tools/tasks/clean.ts

The 'del' function now returns a promise, rather than taking a callback.

Upgraded package 'del' to v 2.x.

---

tsconfig.json

Specifying location for compiled TypeScript .js and .js.map files to go to keep Git clean.

'outDir' added to tsconfig.json

---

gulpfile.ts
package.json

after adding gulp-typedoc we can now build docs

enabling docs build

---

README.md

In Adding custom libraries adding 'my-library' needs a comma preceding it.

'Adding custom libraries' Adding comma

---

tools/config.ts
tools/tasks/build.bundles.ts
tools/tasks/build.test.ts

Hi,
I just migrated a simple demo project of mine to use this angular2-seed project. I had some trouble, though, because my startup file was named `bootstrap.ts` rather than `main.ts`.
By looking at the `config.ts` I found there's a variable `BOOTSTRAP_MODULE`. I changed it like this:
```javascript
export const BOOTSTRAP_MODULE     = ENABLE_HOT_LOADING ? 'hot_loader_main' : 'bootstrap';
```
..but it didn't work. After digging a bit in the configuration, I found that the reason is `main` being hardcoded in a couple of places. This PR fixes this. Obviously this shouldn't be a big deal as ppl could only rename their bootstrap file and it's done :smile:.
The only thing I don't really like is that readability of the `SYSTEM_CONFIG_DEV` in `config.ts` suffers a bit. Not sure if there's a better …

fix: allow to name bootstrap file differently than main.ts

---

gulpfile.ts
karma.conf.js
package.json
protractor.conf.js
src/about/components/about.e2e.ts
tools/config.ts
tools/tasks/build.docs.ts
tools/tasks/build.e2e_test.ts
tools/tasks/build.js.prod.ts
tools/tasks/build.test.ts
tools/tasks/clean.ts

Fixes issue #447 
- Unit tests get compiled to `/dist/test/spec`
- E2e tests get compiled to `/dist/test/e2e`
- Added `TEST_SRC` constant to `config.js`. By default it points to `src`, but allows the possibility to make it point to `test` (thus keeping app source and test source in different folders).

Fix test compilation inconsistency

---

package.json
src/about/components/about.ts
src/app/components/app.ts
src/home/components/home.ts
tools/tasks/build.js.prod.ts
tools/tasks/build.test.ts

- minimum inline-ng2-template plugin minimum version to 0.0.11
- Relative URLs for all components
- inline-ng2-template set to use comp. relative path
resolves #485 
Will squash after review

refactor(Component): URLs relative to component

---

gulpfile.ts
package.json
tools/tasks/npm.ts

During postinstall we start gulp in order to start npm and run `npm prune`
We also clean the dist folder, which is completely irrelevant during install.
I suggest this to change so that the postinstall step directly prunes unused npm
packages.
Since we remove the extra gulp step, it can also shave 2-3 seconds off of a CI
build step.

Cleanup: Cleanup npm from npm

---

gulpfile.ts

This has annoyed me forever. On my machine, calling the custom "task()" method takes roughly half a
second.
Depending on which gulp task you execute, there is no reason to load these tasks in the top of
the gulpfile. I wrap them in a function, which hides the underlying true problem.
The real problem is of course that the loading of tasks take a long time, and hides unused tasks so that we never delete them.
But that will be a separate problem requiring a bigger fix.

(performance) Faster loading of tasks (skip unused)

---

gulpfile.ts

Without passing this function, the clean task would exit before the system was able to delete the requested files.
Fixes #516 gulp clean does not erase files

Pass async done function to clean tasks

---

tslint.json

"no-trailing-comma" has been replaced with "trailing-comma" since v3.0.0.dev.1
[breaking change notice](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v300-dev1)
package.json in master is currently at 3.3.0

Updated trailing-comma rule tslint.json

---

package.json

I haven't seen this error happening on angular2-seed  since it is not using RouterOutlet.
However, I saw the following error without this upgrade on my own project
and I have spent few hours to find this solution. This upgrade would be useful for others.
"Uncaught Uncaught Uncaught ReferenceError: RouterOutlet is not defined"
Typescript:
```
import {Directive, Attribute, ElementRef, DynamicComponentLoader} from 'angular2/core';
import {Router, RouterOutlet, ComponentInstruction} from 'angular2/router';
import {AuthenticationToken} from '../services/security/tokens';
import {CetRouteData} from '../services/cetRouteData';
```
JS generated before upgrade: 
```
var core_1 = require('angular2/core');
var tokens_1 = require('../services/security/tokens');
var cetRouteData_1 = …
```

updated gulp-typescript from 2.8.0 to 2.10.0

---

package.json

- Removes typings when npm run reinstall is executed
> Verified on OSX 10.11.3, Ubuntu 14.04.3 & Windows 10
resolves #545

chore(tools): Remove typings on npm run reinstall

---

package.json

**Patch version**
- Update Typings from 0.6.2 to 0.6.8
- Update ts-node from 0.5.4 to 0.5.5
- Update systemjs-builder from 0.15.7 to 0.15.10
**Minor Version**
- Update tslint from 3.3.0 to 3.5.0
- Update gulp-typescript from 2.10.0 to 2.12.0
- Update gulp-tslint-stylish from 1.0.4 to 1.1.1
- Update serve-static from 1.9.2 to 1.10.2
- Update semver from 5.0.3 to 5.1.0
- Update gulp-sourcemaps from 1.5.2 to 1.6.0
> Verified on OSX 10.11.3, Ubuntu 14.04.3 & Windows 10
resolves #544

chore(tools): Update dev dependencies

---

karma.conf.js
test-main.js

This change makes available for a single file test.
While development, we run a single file unit test over and over again. It would be useful to have a single file test.
This is how it runs. 
For a single file test, just add `--files=FILENAME`. The output would be like thisl
```
angular2-seed (master)$ gulp test --files=app
App component
✔ should work
WARN: 'DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask'
01 03 2016 08:24:56.633:WARN [web-server]: 404: /assets/svg/more.svg
Chrome 48.0.2564 (Mac OS X 10.11.1) WARN: 'DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask'
Finished in 0.217 …
```

made available for a single file test for karma

---

src/app/components/app.component.ts

I wondered what this did and why we have it in the seed project?
ViewEncapsulation.None tells Angular not to use shadow DOM
Does  this make a difference? Did it slow down the code/tests/runtime?
My suggestion is to remove it.
More info http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html

Removed ViewEncapsulation.None (unnecessary)

---

tools/config/project.config.ts
tools/config/seed.config.ts

It took long enough time to find how to extend seed.config.ts (and make injects working), so I want to share this example with other users. There are examples for JS, CSS and SASS files. I also exported `normalizeDependencies` function, because it's really necessary for overriding NPM dependencies.

Add example of project.config.ts code

---

src/app/components/app.component.e2e.ts
tools/config/project.config.ts

Good morning,
the assert `'should have a title'` in `app.component.e2e.ts` currently fails on the latest master.
**Reason:** The assert expects the title to be `'Angular 2 Seed'`, but is actually `'Put name of your app here'` (which was introduced by the commit 598efd5f669def1a9f573007a958912117275d9d)
**Possible solutions:**
_A)_
- Fix the assert in `app.component.e2e.ts` to expect `'My Angular 2 App'` 
- Comment out the `this.APP_TITLE` in `project.config.ts`
_Pro:_ 
- Set expectations in the e2e test to the baseline configuration of the seed
- Commenting out the override in `project.config.ts` to still have the example of how to change the tile, yet not alter the baseline seed configuration
_Con:_
- The override of the project specific app title would be reverted
_B)_
- Fix the assert …

Fixes failing app component e2e test

---

gulpfile.ts
src/shared/services/name-list.service.spec.ts
tools/config/project.config.ts
tools/tasks/seed/build.assets.prod.ts
tools/tasks/seed/build.bundles.app.ts
tools/tasks/seed/build.index.dev.ts
tools/tasks/seed/build.index.prod.ts
tools/tasks/seed/check.versions.ts
tools/tasks/seed/karma.start.ts
tools/utils/seed/code_change_tools.ts
tools/utils/seed/tasks_tools.ts
tools/utils/seed/tsproject.ts
tools/utils/seed/watch.ts
tsconfig.json

Set the flag: `noImplicitAny` to `true` in tsconfig.json
See: https://github.com/angular/angular/issues/4924
When you set the flag to `true`, most errors appear in `gulpfile.ts and the settings:
```bash
Unable to compile TypeScript
gulpfile.ts (12,24): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (22,30): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (29,24): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (39,25): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (52,25): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (62,31): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (69,26): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (76,19): Parameter 'done' …
```

set noImplicitAny to true and fix errors

---

package.json
tools/utils/seed/code_change_tools.ts
tools/utils/seed/server.ts
tools/utils/seed/watch.ts

> BrowserSync was not being notified on file change
- Takes BrowserSync back to last "real" release
- Adds function to notify BrowserSync
- Modifies watch task to notify on change
- Fixes file path semantics on reload()
Resolves #599 
Resolves #611

fix(build): BrowserSync Fix

---

tools/config/seed.config.ts

I needed to add this to match what is in the dev config. Without it when build.bundles.apps runs it won't find packages specified via package.json in the npm dep. 
If I dump the builder config after it's setup I can see it resolves to
```packageConfigPaths: [ 'file:///[path to my app]/node_modules/*/package.json' ],```
so looks like this is how it should be setup.

fix(build.bundles): add packageConfig path to the system builder config

---

tools/config/seed.config.ts

1bd5691 did not fix it, removing `packageConfigPaths` in `SYSTEM_CONFIG_DEV` did not fix it, but also did not break the dev build, so I'm not sure for what this was needed. Doing the same thing in `SYSTEM_BUILDER_CONFIG` fixed the prod build though. Thanks @mgechev for the fast response and the right direction!

fix prod build #712

---

src/sw.js

Old caches will be deleted when a new service worker gets activated, and it is easy to bump the cache version.
SW [cannot cache POST requests](http://stackoverflow.com/questions/35270702/) and no longer registers them as an error (see request method check in the `fetch` event listener).
SW will only go to network if it needs to, and is capable of working offline
*This can be a current sw solution until full progressive support is enabled

Update service worker

---

tools/config/seed.config.ts

`path.join()` normalizes the resulting path anyway. There is no need to call `path.normalize()` explicitly.

refactor(seed.config): remove redundant call to `path.normalize()`

---

tools/config/seed.config.ts

The changes/reverts from #712 left this broken for prod builds again. 
From the looks of the error messages the underlying issue was related to the paths being broken when they were normalized on windows, I think it may of been dropping the * which is supposed to be replaced by the npm module name.
I don't have a windows dev machine to test this on, but this seems to work okay on my mac. I like to imagine it will fix the windows issue from #712 too since it should be providing the full path in the correct format for the OS.

fix(build.bundles): add packageConfigPaths so bundlers will work with modules using package.json

---

package.json

- Moves off of the master branch
- 0.6.1 contains the absolute path fixes needed for the seed
Resolves #762

chore(devDeps): Update rempa-istanbul to 0.6.1

---

tools/tasks/seed/css-lint.ts

Corrects the path for the css-lint task after the refactoring
of the main.css into client/css (before: assets)
Hi there, i am not quite sure if i got this right, but after the commit https://github.com/mgechev/angular2-seed/commit/aa9ad6ab32cf568fcf93f4b5e1c77d095c33c8a2 introduced a dedicated css directory under client/css i think the css-lint task has to point to this new directory.
If i got it wrong, then i am sorry, feel free to abandon this pull request.
Greetings

Fixes path for css-lint task

---

tools/config/seed.config.ts
tools/utils/seed/code_change_tools.ts

Exposes the browserSync configuration to the seed configuration. Can now easily be overridden.

chore(tools): expose browserSync configuration

---

tools/config/seed.config.ts

This one is for the bug where the production build breaks on IE 11 because the shims are not included in the production build.

Including shims in the production build.

---

tools/utils/seed/code_change_tools.ts

Enabling the streaming of css files handled by browsersync.
Will look through the list of changed file and if only css or scss file was changed, then all css files will be internally reloaded per stream by browsersync. If some other file type is found amongst the changed one - a standard  reload will occur.
It works nicely with scss, when a separate task compiles a concat file containing all of the styles and a normal watch will only find the scss files, as they are the ones lying in the project scope.
Note that component scoped css files will not be covered by this as they are loaded by angular directly.
Addresses #804.

perf update -> css streaming

---

tools/config/seed.config.ts
tools/tasks/seed/build.assets.dev.ts
tools/tasks/seed/build.assets.prod.ts
tools/utils/seed/watch.ts

This is a fix for #821 -- ignoring temporary files from editors when
watching and building.

Ignoring editor temporary files

---

tools/config/seed.config.ts

This PR adds the type of "any" to the SYSTEM_CONFIG_DEV and SYSTEM_BUILDER_CONFIG objects in seed.config.ts. Adding these types makes typscript happy and allows for the config objects from project.config.ts to do things like add lodash like it's done in [angular-seed-advanced](https://github.com/NathanWalker/angular2-seed-advanced).
Example:
``` javascript
this.SYSTEM_CONFIG.paths['lodash'] = `${this.APP_BASE}node_modules/lodash/index`;
this.SYSTEM_BUILDER_CONFIG.paths['lodash'] = `node_modules/lodash/index.js`;
```

Adding types to SYSTEM_CONFIG_DEV and SYSTEM_BUILDER_CONFIG objects

---

README.md

Hello guys,
i propose this commit to update the directory and file listing in the README to reflect
the current layout. I saw that before some of the file names were abbreviated with a `...`. I couldn't see a specific reason for this, so i included the full file names, as well as a listing of all the files in the directory structure. If you do not approve of this, feel free to reject the pull request :)
Greetings
Dope

Update directory structure in README.md

---

src/client/app/+about/about.component.ts
src/client/app/+home/home.component.ts
src/client/app/app.component.ts
src/client/app/shared/navbar/navbar.component.ts
src/client/app/shared/toolbar/toolbar.component.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/build.js.test.ts

Hey again guys, sorry, i had to open a new PR since my local rebase failed. 
This commit sets the `moduleId` property of the @Component annotation to enable
`templateUrl` and `styleUrls` to be only the file name without the
surrounding path.
`$ npm start` and using the app in the browser runs fine so far, however `$ npm test` fails:
```bash
[22:27:52] Plumber found unhandled error:
Error in plugin 'gulp-inline-ng2-template'
Message:
ENOENT: no such file or directory, open '/Users/DonDope/Development/GitHub/TheDonDope/angular2-seed/src/client/about.component.html'
Details:
errno: -2
code: ENOENT
syscall: open
path: /Users/DonDope/Development/GitHub/TheDonDope/angular2-seed/src/client/about.component.html
fileName: /Users/DonDope/Development/GitHub/TheDonDope/angular2-seed/src/client/app/+ab …
```

Apply `moduleId` to @Component annotation

---

tools/tasks/seed/build.js.dev.ts
tools/tasks/seed/build.js.e2e.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/build.js.test.ts
tools/tasks/seed/build.js.tools.ts

Fixes typings bundle references in build tools because I evidently suck at `find` in VSCode
//cc @Shyam-Chen 
Resolves #915

hotfix(devDeps): Fix typings bundle paths in js build files

---

test-main.js

Removed `debugger;` statements from test-main.js so that browser debugger doesn't break on them.

chore(tests): remove 'debugger;' statements

---

tools/config/seed.config.ts

it throws the following error:
```Error: SyntaxError: Unexpected token <
at eval (native)
at Object.eval (http://localhost:5555/node_modules/rxjs/Rx.js:6:17)
at eval (http://localhost:5555/node_modules/rxjs/Rx.js:187:4)
at eval (http://localhost:5555/node_modules/rxjs/Rx.js:188:3)
Evaluating http://localhost:5555/node_modules/rxjs/Subject
Evaluating http://localhost:5555/node_modules/rxjs/Rx.js```

Observables of function doesn't work

---

karma.conf.js

Karma was including node_modules spec files. This is not what we want, because:
- we should not test the framework,
- tests may fail so would CI or CD processes.

Excluded node_modules' spec files in karma configuration.

---

src/client/app/shared/name-list/name-list.service.ts

Observable caching in the name-list service was not working as expected.
For instance, if you put that code in the HomeComponent
```ts
constructor(public nameListService: NameListService) {
nameListService.get().subscribe((names) => console.log(names));
nameListService.get().subscribe((names) => console.log(names));
}
```
and inspect the network, you will see the ajax call is triggered twice.
With my fix, it is only called once, as expected.

[bug fix] observable now only get triggered only once as expected

---

README.md
src/client/app/app.component.ts
src/client/app/shared/config/env.config.ts
src/client/app/shared/index.ts
tools/config/seed.config.ts
tools/env/config.json
tools/utils/seed/template_locals.ts

Environment-specific configuration. Doesn't add extra dependencies and is quite handy.
Requested by @jbouzekri.

feat(config): add app environment specific config

---

tools/tasks/seed/build.js.prod.ts

Currently the build.prod will succeed, even when there are TS errors.
I can understand that this is desired behavior on build.dev since the watch would otherwise continuously break. However, to me it makes sense that when running the build.prod it should fail the build. (Since we have the build.prod running in a Jenkins CI)

build.prod task now fails on TS error

---

tools/README.md

I hope you don't mind this extremely trivial PR, it is my first one, so I want to make sure I have the process down before trying anything more substantial.  Here is an [explanation of the change: ](http://www.everythingenglishblog.com/?p=541)
> Also consider words starting with “u.” Some such words make a “y” or consonant sound (e.g., unicorn, unique, and ukulele); in such instances, you should use the article “a” (e.g., a unicorn, a unique store, and a ukulele).

fix 'an/a' typo's  

---

tools/config/seed.config.ts

Allows to import certain rxjs operators such as 'timeInterval' and 'exhaustMap'. Fixes https://github.com/mgechev/angular2-seed/issues/973 and https://github.com/mgechev/angular2-seed/issues/784

fix(config): rxjs package's defaultExtension was set to true, but should be js instead

---

gulpfile.ts
tools/tasks/seed/build.js.test.ts

Related to issue #1086
- Execute build.html_css before build.js.test to satisfy karma
- If using scss, gulp-inline-ng2-template will be unable to find the css files
it needs. Setting the 'supportNonExistentFiles' boolean to true ignores this warning.

fix(1086) silence gulp-inline-ng2-template css warnings

---

package.json
tools/utils/seed/server.ts

Add express compression for `serve.prod`.
I think this make sense, show developers real size of application with gzip compression and loading time. It's very important when you make a visual testing with dev tools and using _throttling_.
Same thing I have add for `unit test` server to speed up unit test run.

Add express compression for Prod and Unit Test Servers

---

tools/config/project.config.ts

Today when I had a question in **gitter** how to add an assets library, I saw that we don't have this one in our `project.config.ts`, many new developers don't know about this important property. So I add it there.

Add APP_ASSETS to project.config.

---

tools/config/seed.config.ts
tools/tasks/seed/build.html_css.ts

This closes #1040, and closes #1107
Apparently it is possible now to run `npm run build.prod` and publish the generated `dist/prod` to a subsite like `http://www.site.com/subsite/` and every related path should be ok.

Fix relative path on build.prod

---

package.json

In some cases we get the RangeError in the build.js.prod but this is fixed in the 2.0.5 version of gulp-inline-ng2-template
`RangeError in plugin 'gulp-inline-ng2-template'
Message:
Maximum call stack size exceeded
Details:`
https://github.com/ludohenin/gulp-inline-ng2-template/issues/45

Updating gulp-inline-ng2-template

---

gulpfile.ts
karma.conf.js
src/client/app/+about/about.component.spec.ts
src/client/app/+home/home.component.spec.ts
src/client/app/+home/home.component.ts
src/client/app/app.component.spec.ts
src/client/testing/router/mock-location-strategy.ts
src/client/testing/router/router-testing-providers.ts
tools/config/seed.config.ts
tools/tasks/seed/build.js.test.ts
tools/tasks/seed/clean.all.ts
tools/tasks/seed/clean.coverage.ts

here's a PR with what I did to get coverage working and the tests updated for RC4. 
after this update you should be able to run `npm test` and `npm run serve.coverage` and have it work as expected. karma should also be able to detect changes properly when running the watch task.
build updates:
update build.js.test task to only build the tests (different build paths invalidate the sourcemaps)
update gulp build.test task to only perform a clean on the initial build and to also run build.js.dev now
add a clean.coverage task and add it to the build.test task
test updates:
remove deprecated jasmine imports
add mock router/location strategy (until @angular provides one)
add default values to home.component so home component tests will pass.
not done:
figure out some way to run istanbul-remap …

fix(coverage): resolve issues preventing coverage/tests running correctly

---

tools/README.md

Update the REAMDE.md in /tools, adding the missing task description
for the `clean.coverage` task and correct the
misspelling for the `server.prod` and `server.start` task.

docs(tools-readme): update tools readme

---

.gitignore

Hi,
As I cloned the repository many times and always added .DS_Store
to my .gitignore, I thought it would be smarter to submit it.
Changes do not affect structure or code.
Regards,

chore(.gitignore): add OS X trash file

---

README.md

Modified README: additional command to run to prevent "too many open files" when running test.watch

docs: updated README.md for EMFILE error when using test.watch (#1233)

---

src/client/app/+about/about.component.spec.ts

TestBed is used due TestComponentBuild is deprecated

refactor(about.component.spec.ts): updating specs to use RC5

---

tslint.json

semicolon expect an array and not only true or false. Fixed it

fix wrong type

---

tools/tasks/seed/karma.watch.ts

Karma watch must wait before file descriptors are available before starting
[Issue #1285](https://github.com/mgechev/angular2-seed/issues/1285)

Karma watch waits for an available file handler

---

tools/utils/seed/template_locals.ts

It is better to log the actual error message, because a exception can have different causes. 
For example: In the current implementation a syntax error, in a config file, will produce 'Cannot find ${configPath}'. Because this is misleading, this commit changes the behavior to log the actual exception message (f. e. 'Unable to compile TypeScript').

Log exception message instead of generic error message

---

tools/config/seed.config.ts
tools/tasks/seed/build.js.dev.ts
tools/tasks/seed/build.js.e2e.ts
tools/tasks/seed/build.js.prod.ts

In case of multi-app scenario, non AoT builds will skip only main app's main-prod.ts file. This commit will ensure that all main-prod.ts in APP_SRC will be skipped in transpiling process (build.js.dev, build.js.prod and build.js.e2e)

Skip main-prod.ts in non-AoT build for multi-app scenario. Fix for #1305

---

package.json

`"es6-module-loader": "^0.17.8",` is deprecated and should be changed to `"es-module-loader": "^1.0.0",`

"es6-module-loader": "^0.17.8, is deprecated.

---

tools/tasks/seed/build.assets.prod.ts

When running `build.prod` the `tsconfig.json` file was copied over into `dist/prod`. This file can be excluded.

fix(build.assets.prod) excluding tsconfig.json

---

package.json
src/client/tsconfig.json

This pull request fixes issues mentioned in issue #1366 Protractor Typings.
Reversed the recent commit to the src/client/tsconfig.json which broke the build.
This was presenting itself as many errors of the form: "error TS2300: Duplicate identifier ..."
The 2.53 version of the @types/selenium-webdriver breaks compatibility with version 2.44.
This breaking change wrecked the build for protractor, so I pinned the version to 2.44.*.

Fix for Issue "#1366: Protractor typings"

---

tools/config/seed.config.ts

In SYSTEM_CONFIG_DEV the configuration of each angular bundle should not be necessary since the bundles are the main files of the node packages.
In SYSTEM_BUILDER_CONFIG loading of the package.json files didn't work because of the missing path `'node_modules/*': 'node_modules/*',`. Bundling then works fine without configuring each package.

Removed package configuration and fixed loading of package.json files

---

tools/tasks/seed/build.js.prod.exp.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/copy.prod.ts
tools/utils/seed/tsproject.ts

In order to make use of the Typescript 2 feature of BaseUrl and Path mappings, it seems necessary to copy the tsconfig.json file to the tmp dir.
We got the error message `error TS2345: Argument of type 'Session' is not assignable to parameter of type 'BaseModel'.  Property 'propertyMap' is protected but type 'BaseModel' is not a class derived from 'BaseModel'.` which seems to be caused because of the following configuration in tsconfig.json:
```
"baseUrl": "./src/client",
"paths": {
"shared/*": [
"app/shared/*"
],
"core/*": [
"app/core/*"
]
}
```
Because tsconfig.json is located in src/client, it takes all imports starting with `shared` from the src/client folder and not from tmp. Which seems to cause that the types don't match.
If tsconfig.json is located in tmp, then it will take the …

copy tsconfig.json to tmp dir

---

src/client/app/app.component.ts
src/client/app/home/home.component.ts
src/client/app/operators.ts
src/client/app/shared/name-list/name-list.service.ts
tools/manual_typings/seed/operators.d.ts

RXJS/NGRX operators must be added to the application by importing them like ` import 'rxjs/add/operator/map';`. If, like in our application, operators are used a lot, they have to be imported often.
We would like to have one central place where all needed operators are added. Because those operators might be used in tests as well, their types definitions must be available in `build.js.test.ts`. For this purpose I import the operator definitions in a manual typings file.
Are there better solutions for this?

Add all needed rxjs/ngrx operators to one central file

---

tools/config/seed.config.ts
tools/tasks/seed/karma.run.ts

In order to keep the build tasks up-to-date with the seed project, it is easier to have all customization options in the config.

Moved karma reporters config from task to config for easier customization

---

package.json
tools/config/seed.config.ts
tools/tasks/seed/build.bundle.rxjs.ts
tools/tasks/seed/build.bundles.app.exp.ts
tools/tasks/seed/build.bundles.app.ts

see https://github.com/angular/angular/issues/9359
Reduces the number of initial HTTP requests in dev mode from 115 to 63. In a larger app this significantly reduces the initial loading time of the app.

Build systemjs compatible rxjs bundle in order to reduce loading time in DEV mode

---

tools/tasks/seed/karma.run.with_coverage.ts
tools/tasks/seed/serve.coverage.watch.ts

These scaffolding files also skew with the test coverage. Related to #1406

Exclude *.routes.ts from test coverage

---

.gitignore

ts-node is installed locally, is not necessary to track ts-node folder

chore: ignore ts-node folder

---

tools/tasks/seed/build.assets.dev.ts
tools/tasks/seed/build.assets.prod.ts

The seed is already dealing with scss files but not with sass files. Since the functionality is already there to use sass files with the seed, it would be nice to handle them as well.

fix(sass): not moving .sass files to dist/* folder

---

package.json

[systemjs](https://www.npmjs.com/package/systemjs) is now at v0.19.39. Let's use it!

Bump version of systemjs dependency

---

tools/tasks/assets_task.ts
tools/tasks/css_task.ts
tools/tasks/seed/build.assets.dev.ts
tools/tasks/seed/build.bundle.rxjs.ts
tools/tasks/seed/build.html_css.ts
tools/tasks/seed/build.js.dev.ts
tools/tasks/task.ts
tools/tasks/typescript_task.ts
tools/utils/seed/code_change_tools.ts
tools/utils/seed/tasks_tools.ts
tools/utils/seed/watch.ts

In dev executes tasks only when a specific file type has changed.
Fix #1432.

feat(tools): do not invoke tasks if not necessary

---

tools/config/seed.config.interfaces.ts
tools/config/seed.config.ts

Ofter we need to extend list of libraries for system config which are in `SYSTEM_CONFIG_DEV` and/or `SYSTEM_BUILDER_CONFIG`.
Method will provide short way to add it.
Can be called from project config constructor
``` ts
this.addPackageBundles({
name: 'angular2-modal/plugins/bootstrap',
path: 'node_modules/angular2-modal/bundles/angular2-modal.bootstrap.umd.js',
packageMeta: {
main: 'index.js',
defaultExtension: 'js'
}
});
```

Seed config method to extend system config with other libraries.

---

src/client/app/shared/name-list/name-list.service.ts

without the rxjs imports, re-throwing error in `handleError` results in a `TypeError: Observable_1.Observable.throw is not a function`
I have also added in the `do` debugging lib (commented out) as its a handy tool to point out to dev's who are not familiar with rxjs (like myself)

Fix `TypeError` when trying to re-throw

---

tools/config/seed.config.ts

In my case `APP_SRC` was set to `src` (no `/client`). I was getting an error on `npm install` because `prepareBuilderConfig()` runs whenever `ProjectConfig` is instantiated. I also could not override it because it runs before the `ProjectConfig` constructor and before any `ProjectConfig` properties are set.

Fix issue where prepareBuilderConfig() ignores PROJECT_ROOT/APP_SRC/TMP_DIR

---

.docker/dist-build.development.dockerfile
.docker/dist-build.production.dockerfile
.dockerignore
.github/ISSUE_TEMPLATE.md
docker-compose.production.yml
docker-compose.yml

As requested in #1422 this commit provides a basic setup for docker deployment.
- Have `docker-engine` and `docker-compose` installed
- Have a fresh clone of the project
- Right after cloning (do not run `$ npm install`, it is not neccessary), `cd` into the folder and run one of the below listed deployments.
For development deployment (`$ npm start` in a docker container) run the following (it will use the `docker-compose.yml`):
```bash
$ docker-compose build
$ docker-compose up -d
```
Open browser at http://localhost:5555/
For production deployment (`$ npm run serve.prod` in a docker container) run the following (explicitly using the `docker-compose.production.yml`):
```bash
$ docker-compose -f docker-compose.production.yml build
$ docker-compose -f docker-compose.production.yml up -d …
```

chore(build): provide docker support

---

tools/tasks/seed/build.js.prod.ts

When running build.prod in a windows environment we were receiving the following error:
```
[...]
Starting 'build.js.prod'...
error TS1125: Hexadecimal digit expected.
```
Traced it down to being caused by https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/build.js.prod.ts#L29
Adding the appropriate target resolved the issue. Target should be coming from tsconfig.json, but that feature should be added to https://github.com/ludohenin/gulp-inline-ng2-template

Set inline target to be es5

---

src/client/index.html

It's difficult to figure out what error occurred from the console with zones sometimes. Here's the before and after with this PR.
Before:
After:
Code added about.component to produce this error:

Better stack trace messages in dev mode

---

appveyor.yml

I guess caching should be possible if it is invalidated in case package.json changes

cache node_modules with dependency to package.json

---

yarn.lock

I fetched the latest version of the seed and updated my dependencies with a `yarn install`. The committed file is the result of it

chore: updated yarn.lock after install

---

.vscode/settings.json

settings file for vscode. Assures that vscode is using the same ts compiler as specified in `node_modules/typescript/lib`

chore: using ts lib in node_modules for vscode

---

karma.conf.js
package.json

To enable run specific test
https://github.com/mgechev/angular-seed/issues/1585

add minimatch to run a specific tests

---

tools/config/seed.config.ts

Some npm run-scripts contain multiple gulp comman-
ds (ex. e2e.ci). Multiple gulp commands may refer-
ence the ENABLE_SCSS setting; however, '--scss' is
only appended to the final command:
gulp ... && gulp ... && gulp ... "--scss"
This results in a build error.
To provide each command in an npm run-script the
correct ENABLE_SCSS setting, set the ENABLE_SCSS
setting using an environment variable rather than
a command-line argument.
BREAKING CHANGES
1. The '--scss' no longer has any effect
2. To enable SASS support via the command line,
one must prefix their run-script command with
ENABLE_SCSS=1 or ENABLE_SCSS=true.

Specify ENABLE_SCSS setting via environment variable

---

src/client/app/app.component.ts
src/client/app/home/home.component.ts
src/client/app/operators.ts
src/client/app/shared/name-list/name-list.service.ts
src/client/app/shared/navbar/navbar.component.ts
src/client/app/shared/toolbar/toolbar.component.ts
src/client/index.html

- removed comment in app.component.ts which seems to be outdated
- removed extra blank line between decoration and class (+ 1 whitespace fix)
- uncommented import of throw in operators.ts and removed it in name-list.service.ts instead

a few cleanups

---

.vscode/tasks.json

Might be helpful for others as well. Running tslint via vscode task shows all the errors in the Problems pane

chore: add vscode task for tslint

---

tools/tasks/seed/compile.ahead.prod.ts

depencency tsc-wrapped was removed, which gives an error in prod.exp

missing tsc-wrapped error

---

gulpfile.ts
protractor.conf.js
src/e2e/specs/about.component.e2e-spec.ts
src/e2e/specs/app.component.e2e-spec.ts
src/e2e/specs/home.component.e2e-spec.ts
src/e2e/tsconfig.json
tools/config/seed.config.ts
tools/tasks/seed/build.js.e2e.ts
tools/tasks/seed/clean.e2e.ts
tools/tasks/seed/tslint.ts
tools/tasks/seed/watch.e2e.ts
tools/utils/seed/tsproject.ts
tools/utils/seed/watch.ts

This is originated in advanced-seed project 
https://github.com/NathanWalker/angular-seed-advanced/pull/306
Async/Await is only supported in es2015+ target (and it doesn't seem to be supported for es5 anytime soon) but that's a very nice and neat feature for writing e2e tests as many constructs in nodejs selenium is based on promises and as tests are getting more complicated more and more friction is expected when using promises.
In order to do that e2e tests should be built with another tsconfig.json file. But we still want to compile the main application for es5
This PR consist of the following (slight changes from the angular-seed-advanced project)
- e2e tests and framework moved outside of client folder into e2e folder. This is required to support proper detection of another project …

Implement async/await for e2e tests

---

tools/config/seed.config.ts
tools/tasks/seed/e2e.ts
tools/utils/seed/server.ts

This change allows to add several proxy middleware configurations by adding them in project.config.ts only.
Without this change we had to add the middlewares in project.config.ts, e2e.ts and server.ts

Simplify proxy middleware configuration

---

tools/utils/seed/template_locals.ts

IMO it is helpful to see which environment name is invalid

improve error message about unknown env name

---

.vscode/settings.json

I usually do not want to search in those folders since they are generated. Maybe there are even more?

chore: ignore generated code from vscode search

---

docker-compose.production.yml

Just a small fix in docker configuration for production. The file name of template was wrong so the docker could not start properly.

Fix nginx template file name in docker-compose.production.yml

---

tools/tasks/seed/compile.ahead.prod.ts

As of angular/angular [b15039d](https://github.com/angular/angular/blob/b15039d228d206c8c460eca81af51a78f2fec12e/modules/%40angular/compiler-cli/src/codegen.ts) the 'transitiveModules' option has
been removed from compiler-cli CodeGenerator's 'codegen' method.
The current seed still includes this option, which causes the production AoT build to fail. 
Removing the option -- just like has been done in the angular-cli source code -- allows the production AoT build to execute successfully.

Fix failing AoT build

---

tools/tasks/seed/compile.ahead.prod.ts

This is a revert of 35f1ebe8c7b7488419179a9ab484b8b0f54c8347  needed for
``` npm run  build.prod.exp```
* 35f1ebe8c7b7488419179a9ab484b8b0f54c8347  was needed for angular 2.2.2
* revert needed for 2.2.3

AOT compile fix for angular 2.2.3

---

tools/tasks/seed/build.index.dev.ts
tools/tasks/seed/build.index.prod.ts
tools/tasks/seed/build.js.dev.ts
tools/tasks/seed/build.js.e2e.ts
tools/tasks/seed/build.js.prod.exp.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/build.tools.ts
tools/utils/seed/template_locals.ts

- the builder enables easier configuration without code duplication
- removed the side effects of `Object.assign` by introducing a new object `locals`
(ENV_CONFIG was added to Config previously)
- using a un-stringified ENV_CONFIG to build index.html enables to refer to
properties in index.html by <%= ENV_CONFIG.MY_PROPERTY %>

refactor template_locals using builder

---

.vscode/tasks.json
tools/tasks/seed/tslint.ts

- gulp-tslint does no longer emit the rule name in the error message and therefore I had to fix the regexp for the corresponding vscode task
- `npm run lint` did no longer show the full relative path (starting from the project directory) -- might be that was actually never the case. Fixed it by adding `base` to the option of `gulp.src`. This fix is actually necessary in order that the tslint task for vscode works as expected. Without it, the linking between error and file does not work correctly.

chore: vscode tslint task fixed

---

.vscode/tasks.json
package.json
tools/tasks/seed/e2e.ts

- thus added a `-e` option to the tslint command
- fixed the tslint task for vscode
- and fixed a tslint issue "missing whitespace"

tslint should not lint d.ts files

---

package.json
tools/tasks/seed/tslint.ts

I simply added the latest version of gulp-tslint back into package.json and reverted the gulp task for tslint back to its former state. npm install and test both run and pass. tslint task was able to find issues when manually introduced into the code.
PR where dependency was removed: https://github.com/mgechev/angular-seed/pull/1681

Add gulp-tslint back in. It now supports tslint v4

---

package.json

Router should be set to version compatible with other Angular 2.3.x packages. TSLint needed to be set to 4.0.x because codelyzer requires that.

Modify tslint / @angular/router package versions to fix NPM warnings

---

index.md

Fixed tools/readme.MD link in documentation

---

src/e2e/specs/about.component.e2e-spec.ts
src/e2e/specs/app.component.e2e-spec.ts
src/e2e/specs/home.component.e2e-spec.ts

TS2304 errors are occurring during the e2e.ci task:
src/e2e/specs/about.component.e2e-spec.ts(4,18): error TS2304: Cannot find name 'browser'.
...
The webstorm editor also shows import error warnings, which can be
distracting.
This may be because @types/protractor was removed. The 'protractor'
module now contains the necessary typings.
Adding an import statement silenced the webstorm editor warnings as
well as the TS2304 warnings that occurred during e2e.ci execution.

Add protractor import statements to e2e specs

---

tools/config/seed.config.ts

Sample code in about component:
```typescript
export class AboutComponent {
ngOnInit() {
setTimeout(() => {
throw new Error('blah1');
}, 2000);
setTimeout(() => {
throw new Error('blah2');
}, 2000);
setTimeout(() => {
throw new Error('blah3');
}, 2000);
}
}
```
Error without long stack trace:
Error with long stack trace:

feat: zone.js long stack traces for dev

---

tools/config/seed.config.ts
tools/utils/seed/watch.ts

Allow users to use project settings to include external directories aside from app src directory to trigger compilation.
Example config from actual project:
Useful for when coupled with gulp-sass includePaths settings:

feat: User defined watch paths

---

src/client/tsconfig.json

When upgrading to protractor v5.1.1 the typings cause problems during AoT compilation.
```
Error: Error encountered resolving symbol values statically. Could not resolve events relative to projectdir/node_modules/blocking-proxy/built/lib/webdriver_commands.d.ts., resolving symbol WebDriverCommand in projectdir/node_modules/blocking-proxy/built/lib/webdriver_commands.d.ts
at simplifyInContext (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25795:27)
at StaticReflector.simplify (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25807:17)
at StaticReflector.annotations (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25299:84)
at NgModuleResolver.resolve (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:17783:86)
at …
```

Remove protractor from client/tsconfig.json

---

src/client/app/app.component.css
src/client/app/app.component.ts
src/client/app/shared/navbar/navbar.component.css
src/client/css/main.css

I was having difficulty sizing the content of the page to fill the remaining space. You can try this by applying `height: 100%` to the `:host` css property. By adjusting the body to act as a flexbox container a component can fill it's size using `flex-basis: 100%`. Example usage on my [login-form branch](https://github.com/Karasuni/angular-seed/tree/login-form).

flexbox layout for height:100% fix

---

README.md
package.json
src/client/app/main-prod.ts
src/client/app/main.ts
src/client/ngsw-manifest.json
tools/config/seed.config.ts
tools/config/seed.tasks.json
tools/tasks/seed/build.assets.dev.ts
tools/tasks/seed/build.assets.prod.ts
tools/tasks/seed/sw.manifest.static.ts

I'm not completely sure that this is ready to merge, it hasn't been terribly well tested and it's not very configurable.
Things that might be nice to add configuration options for:
- Ability to enable/disable service worker in the build process
- Ability to control what files are added to the static files manifest
Have a look at this, and let me know your thoughts.

Adds Support For Angular Mobile Toolkit Service Worker

---

tools/config/seed.config.ts

For extra modules, where the package.json is located at different place, we should be able to add those paths. If not done, this would lead to buld.prod failure.

Adding helpful comments to the config

---

tools/config/seed.config.ts

In order to import BrowserAnimationsModule, the bundle platform-browser-animations.umd.js should be available on path @angular/platform-browser/animations.
Without the import animations won't work.

Add platform-browser-animations.umd.js to builder config

---

package.json

I found it useful for other developers who use angular-seed to build their own apps.
I've just worked on localization for our app and can't get why it generate empty file. But this line is fixing issue. Other things from this instruction https://github.com/mgechev/angular-seed/wiki/Enabling-Angular-i18n-native are correct and very helpful.

Small fix to make possible generate not empty message file for localization

---

tools/config/project.config.ts
tools/config/seed.config.ts
tools/tasks/seed/build.bundles.app.rollup.aot.ts

We came across a few dependencies where we had to edit this seed task to include in rollup. We would rather follow the pattern of supplying the config via project.config w/out editing the seed task. Let us know what you think.
Thanks

provide rollup includes and named exports in project config

---

README.md

Adds a link to a fork demonstrating how to integrate with Kendo UI for Angular.

docs: add link to Kendo UI for Angular fork

---

tools/tasks/seed/build.html_css.ts

Just like it's done for the CSS files, SCSS files should also only
cached on production build. As things were before this patch, I would
not get a rebuild of my SCSS files (as per the progeny dependency tree)
when I updated one of them. This was problematic when working in `npm
start` or `npm run start.deving` mode, and resulted in broken UI that

fix(tools): cache SCSS files only in prod build

---

README.md
package.json

- Updated the link of `ngx-translate`;
- Removed the `@types/zone.js`:
`npm WARN deprecated @types/zone.js@0.5.12: This is a stub types definition for Zone.js (https://github.com/angular/zone.js). Zone.js provides its own type definitions, so you don't need @types/zone.js installed!`
It doesn't seem to be necessary, as the **WARN** above says... you can simply install **zone.js**.

Update ngx-translate link and remove @types/zone.js

---

tools/config/seed.tasks.json
tools/tasks/seed/karma.run.ts
tools/tasks/seed/karma.run.without_coverage.ts
tools/tasks/seed/test.watch.ts
tools/utils/seed/server.ts

Fix for #1894 
- moved watchAppFiles from start.deving to server to make it usable project-wide
- added test.watch as custom command which behaves similar to start.deving
- added karma.run.without_coverage, but not sure if we also just can run the karma.run.with_coverage in order to keep the codebase a bit leaner (not sure what the performance impact is)
Suggestions are welcome :-)

Refactored test.watch to behave like start.deving, fixes #1894

---

tools/tasks/seed/i18n.merge.ts

Automatic update location path of `messages.xlf` file when run i18n command.

Fix escaped string of i18n & correct location path

---

package.json
yarn.lock

Per comment from @Karasuni,
```
[23:36:06] Starting 'build.js.dev'...
C:/dev/angular-seed/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
Types of property 'lift' are incompatible.
Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
Type 'Observable<T>' is not assignable to type 'Observable<R>'.
Type 'T' is not assignable to type 'R'.
[23:36:10] TypeScript: 1 semantic error
[23:36:10] TypeScript: emit succeeded (with errors)
```
And per error log from AppVeyor:
```
[03:25:03] Starting 'compile.ahead.prod'...
Error: Error at C:/projects/angular2-seed/node_modules/rxjs/Subject.d.ts:16:22: Class 'Subject<T>' incorrectly extends base class …
```

Bug fix with rxjs 5.4.1

---

docker-compose.yml

The current docker development configuration only copies the users code into the container in the build process. New changes to the code are not copied and therefore the watchers and livereload does not work.
This PR mounts the project directory on the host to the container, allowing you to modify the code without having to rebuild the image. It does not sync the `node_modules` folder to avoid conflicts of OS specific packages and bindings.

Sync local changes with docker container

---

tools/utils/seed/server.ts

Bug introduced in 215bdbf610cd3c11624de3e5b0132660677d03bd
Also revert using the same port for serving docs, coverage and prod.

Fix web browser not opening on serve tasks

---

tools/config/seed.config.ts

include APP_ASSETS before building css/scss of seed so we can include libraries like bootstrap and not have our custom styles for that library overridden.

fix: css asset ordering

---

tools/config/seed.config.ts

Angular's http client from @ angular/common/http should be a dependency in the seed config, not in the project config as pointed out in #2057.

Added dependencies for Angular's  http client

---

package.json

Resolves #2114
[This change](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/302970129c1698a5072e1fc94bf6cd813b554185) seems to have broken typings the way it's currently used in tasks (it's expecting `util.colors.default.foo`)

chore: fix gulp-util types version (#2114)

---

package.json

The original cause of issue #2114 appears to have been fixed so #2115 can effectively be reverted and semver latest can start being used again.
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/0fca415085b80f3de023a02733ed7c39b9e3fbe0

chore: Update gulp-util types

---

tools/config/seed.config.ts

Production is broken when importing RxJS operators be referencing 'rxjs/operators?.
seed.config.ts is pointing to a file that does not exist in RxJS 5.5.x.

Fix production build when importing RxJS operators

---

README.md

It looks like the Angular.io site has moved things and the Style Guide is now located at (https://angular.io/guide/styleguide). I have updated the main README.md to ensure it contains the correct link.

Update link for Angular StyleGuide in README.md

---

package-lock.json
package.json

Despite the fact that the package 'browserslist' is a transitive dependency of:
- autoprefixer@9.0.1
- cssnano@4.0.3
It needs to be added manually to our package.json to be installed in the docker environment. This issue doesn't seem related to 'optionalDependencies' since, for example, the dependency from `autoprefixer` is compulsory.

Fix docker build

---

.docker/Dockerfile_prod
.docker/rm.optional.deps.js
.docker/rm.optional.types.js

There is no need to bust the "npm install" cache layer if only the app
source files have changed. This only applies to the prod image.

Improve production docker build - make better use of layer cache

---

package-lock.json
package.json

It appears karma versions above version 2.0.2 (e.g. 2.0.5 or 3.0.0) may need a change in the build scripts currently there. This is a temporary fix until someone looks into fixing whatever the issue may be and ideally migrating to Karma 3.
For example, with karma version 2.0.3, the coverage page will load before the tests are loaded resulting in a page that says `Cannot GET /`, and needs to be refreshed after the tests are loaded.
It will also generate the error 
```
SUMMARY:
√ 5 tests completed
TOTAL: 5 SUCCESS
[15:07:24] 'karma.run.with_coverage' errored after 6.62 s
[15:07:24] Error: task completion callback called too many times
at finish (C:\git\angular-seed\node_modules\orchestrator\lib\runTask.js:15:10)
at cb (C:\git\angular-seed\node_modules\orchestrator\lib\runTask.js:29:3)
at …
```

Made karma version static
