gulpfile.js
package.json
templates/sample-app.html
ts/app.ts
ts/services/NameList.ts
tsconfig.json
tsd.json
typings/angular2/angular2.d.ts
typings/tsd.d.ts

* `js` files migrated to `ts`.
* gulp file updated, gulp-traceur no more required, traceur-runtime taken from angular2 pkg.
* `.d.ts` file added (angular2.d.ts is a customized one found on github somewhere, to be updated as needed)

Migrated to Typescript

---

gulpfile.js
index.html
ts/app.ts

@mgechev I've added a very simple router. If you want to have a look before merging the 2 branches.

Added router

---

ts/app.ts

The newName property is the SampleApp class is not used. It's a little confusing since the parameter to addnew is named "newname" as well.

newName property in SampleApp class in unused

---

app/components/about/about.html
app/components/about/about.ts
app/services/NameList.ts

Used TypeScript shorthand.
Removed names property and referenced the list in the template.

Simplify About component code

---

app/app.ts

Remove unused ngFor class

---

gulpfile.js
package.json

Fix for #41 
@ludohenin would you take a look and merge if you think its fine.

Add livereload for prod and dev

---

.gitignore
gulpfile.js

I have extended the Configuration variables and used them to define the PATH. Like this we can just do changes to the paths at one point. So we can now change the source and destination paths easily.
I have also added a folder created by webstorm in the .gitignore.

Gulp src reference

---

app/components/about/about_spec.ts
app/components/home/home_spec.ts
app/typings/ng2_test.d.ts
test-main.js

Fixing test failure due to angular2 dom location change

---

gulpfile.js
package.json

@ludohenin this fixes problems with npm 3.x from our side. Waiting for `tiny-lr` to publish their changes.

fix(build): npm3

---

app/components/home/home.css
app/components/home/home.html
app/components/home/home.ts

Adding related CSS inside of component folder, that way all assets required by component can stay at same level.

component specific css example

---

tools/workflow.config.js

Reverts mgechev/angular2-seed#117

Revert "Add system-polyfills file to the lib/ dist directory"

---

package.json

Update to Angular 2 aplha.40. Everything worked out of the box, without any breaking changes.

Update to angular2 alpha40

---

app/app.ts
app/components/about/about.ts
app/components/home/home.ts

Sounds like @View will be deprecated at some point in the future.
Also, just using @Component is more clear, not to mention easier to teach and explain to others.

Using @Component and dropping usage of @View

---

package.json
tools/workflow.config.ts

Safari throws the following error because angular2 references `startsWith` which doesn't exist. 
I've replaces es6-module-loader with es6-shim(https://github.com/paulmillr/es6-shim).
Question:
```
[Error] EXCEPTION: TypeError: undefined is not an object (evaluating 'styles.forEach')
logError (angular2.dev.js, line 19115)
logGroup (angular2.dev.js, line 19126)
call (angular2.dev.js, line 4440)
(anonymous function) (angular2.dev.js, line 19823)
_onError (angular2.dev.js, line 10639)
onError (angular2.dev.js, line 10558)
run (angular2.dev.js, line 141)
(anonymous function) (angular2.dev.js, line 10572)
zoneBoundFn (angular2.dev.js, line 111)
lib$es6$promise$$internal$$tryCatch (angular2.dev.js, line 1507)
lib$es6$promise$$internal$$invokeCallback (angular2.dev.js, line 1519) …
```

(fix): Uses es6-shim to fix 'undefined' errors in Safari

---

CONTRIBUTING.MD
README.md

Added contributing guidelines

---

app/bootstrap.ts
app/components/about/about_spec.ts
app/components/app/app.ts

Updating deprecated 'bindings' to 'providers'

---

gulpfile.ts
package.json
tools/tasks/check.versions.ts
tsconfig.json

* re-add compileOnSave option in tsconfig (needed for Atom -and
probably more- users)
* simplify check task & rename check.versions
* styles

Minor Fixes

---

karma.conf.js
package.json

Updating to alpha 45 with test fixes

---

app/components/app/app_spec.ts
karma.conf.js

This was inspired by https://github.com/angular/angular/blob/master/modules/angular2/test/router/integration/router_link_spec.ts

test component that uses Router

---

.gitignore
app/bootstrap.ts
app/index.html
gulpfile.ts
package.json
tools/config.ts
tools/tasks/build.bundles.ts
tools/tasks/build.deps.ts
tools/tasks/build.html_css.prod.ts
tools/tasks/build.images.dev.ts
tools/tasks/build.index.ts
tools/tasks/build.js.prod.ts
tools/tasks/clean.ts
tools/typings/merge-stream.d.ts
tools/typings/systemjs-builder.d.ts
tools/utils.ts
tools/utils/template-injectables.ts
tools/utils/template-locals.ts

* Bundles the app and all dependencies (except angular2/RxJS itself)
* Bundling and lazy loading ready
__Edit:__
Some optimization is still needed.

Add production build

---

gulpfile.ts
package.json
tools/config.ts
tools/tasks/check.versions.ts
tools/utils/tasks-tools.ts

Fix prod build

---

karma.conf.js
package.json
test-main.js
tools/utils.ts
tools/utils/task_utils/task_cache.ts
tools/utils/tasks_tools.ts
tsd.json

The current build in master is very slow because of:
- Introduced new set of tasks for the production build
- `ts-node` 5.4 seems a bit slower
Loading tasks on demand. Improve the initial build from 14 seconds to 8 seconds. Also provides better feedback to the user.

Performance improvements in the build

---

gulpfile.ts
tools/utils/tasks_tools.ts

Reverts mgechev/angular2-seed#313

Revert "Lazy load gulp tasks"

---

tools/utils/server.ts

It would be very helpful to know which port is running from the startup task

add logs for server startup

---

tsconfig.json

Reverts mgechev/angular2-seed#349

Revert "'outDir' added to tsconfig.json"

---

README.md

I had forgotten to add the example to the Readme.md... sorry.

Added Highcharts example to the Readme.md

---

tools/config.ts

Speeding app start

---

tools/config.ts

Reverts mgechev/angular2-seed#401

Revert "Speeding app start"

---

README.md
protractor.conf.js
src/about/components/about.e2e.ts
src/app/components/app.e2e.ts
src/home/components/home.e2e.ts

Fixed URLs for e2e tests

---

.gitignore
gulpfile.ts
package.json
src/index.html
src/main.ts
tools/config.ts
tools/manual_typings/systemjs-builder.d.ts
tools/tasks/build.bundles.app.ts
tools/tasks/build.bundles.ts
typings.json

Should fix #473 & #479 
If multiple-bundle ready task is wanted, I can adjust it.

Change build prod from Browserify to SystemJS

---

tools/tasks/build.js.prod.ts

Update inline templates plugin

---

tools/tasks/build.index.prod.ts

prod build cache buster

---

tools/tasks/build.index.prod.ts

I was troubled trying to rebase the first PR. This should work fine now, I hope.

Strip first two directories instead of keeping the last two

---

src/main.ts

chore: Fix APP_BASE_HREF

---

package.json
tools/config.ts
tslint.json

[gulp-inline-ng2-template](https://github.com/ludohenin/gulp-inline-ng2-template) now allow to you to process templates and styles.

chore: Update gulp-inline-ng2-template

---

src/index.html

Add base tag so navigation won't break when the app base is other than the root domain.

Add base tag to index.html

---

tools/config.ts

This is a temporary patch to resolve issues with IE browsers. See #510 #548 and https://github.com/angular/angular/issues/7144

(fix): IE shims patch

---

karma.conf.js

Angular2.0.0-beta.7 IE 11 polyfills
see https://github.com/mgechev/angular2-seed/pull/552 and https://github.com/angular/angular/issues/7144

karma also needs fix form #552

---

test-main.js

Just a small typo I spotted when reading through the latest commits.

Fixes a comment typo

---

tools/utils/code_change_tools.ts

fixes the routes when --base is specified on server start

fix: browserSync server routes with APP_BASE

---

src/index.html

From https://github.com/angular/angular/pull/6944/files (I've tested it in IE and it works)

Fix for IE

---

package.json

> Pretty benign update, none of the breaking changes & updates should have an effect on the seed.
- es6-shim - Same version as Beta.7
- reflect-metadata - Same version as Beta.7
- rxjs - Same version as Beta.7
- zone.js - Same version as Beta.7
resolves #571

chore(Core Deps): Update to Angular 2.0.0-beta.8

---

package.json

> serve.prod removed from npm scripts list
resolves #575

fix(tools): removes serve.prod

---

README.md

Good day to you!
I just offer a minor fix for a broken link within the README.md.
This is my first pull request to a public Github repository, i hope i did it correctly :)
Greetings
Christian

Fix CONTRIBUTING.md link in README.md

---

tools/tasks/seed/build.js.dev.ts
tools/tasks/seed/build.js.e2e.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/build.js.test.ts
tools/tasks/seed/build.js.tools.ts

I needed to change the TOOLS_DIR value and discovered it was still hardcoded in some files. Just corrected that.

Replace hardcoded tools path by TOOLS_DIR constant

---

tools/utils/seed/tsproject.ts

https://github.com/airbnb/javascript#whitespace--around-keywords

Minor change according to Airbnb JavaScript Style Guide

---

package.json

- Removes rimraf
- Uses git to clean the base folder
- Respects and non-git dot files
Fix for #616

fix(build): OS agnostic reinstall task

---

tools/tasks/seed/clean.tools.ts

Adds types to functions in clean.tools.ts
resolves #618

fix(build.tools): Fixes typescript compile

---

tools/utils/seed/clean.ts

- paths variable was never assigned to pathsArray unless it wasn't typeOf array
resolves #610

fix(build.prod) Fix undefined in clean.ts

---

README.md

@mgechev My thinking here is many could learn how to extend this seed from examining the advanced seed and/or if they are seeking a more advanced seed option, this would give them a path to find it easier. The advanced seed is really a nice compliment to this seed :+1:  It's not for everybody but definitely an option that should go hand-in-hand with this seed.

docs(readme): note about advanced seed option

---

README.md

Tagged Alpha0 today, happy day for me :)

docs(readme): angular2-seed angular2-material integration fork

---

package.json

- Update to 2.0.0-beta.10
- Adds es6-promise
- Update to zonejs 0.6.4
> There are a few issues that need to be resolved before this lands. I'll watch upstream and update the branch when it's ready. (See the comment in #648)

chore(deps): Update to Angular2 Beta 10

---

package.json
tsconfig.json

>Last set of dependency maintenance: ts-node
- Includes a change to tsconfig related to exclude semantics to prevent duplicate typings errors 
Resolves #660

chore(deps): Update ts-node to 0.6.2

---

src/about/components/about.component.e2e.ts

fix about-e2e (preprotractor ci)

---

README.md

Link to seed for extending existing postcss / stylelint tooling to add sass-like & cssnext features

Update readme for PostCSS Extension link

---

src/client/app/+home/components/home.component.ts

update directory prefix for template & style urls for consistency with: https://github.com/mgechev/angular2-seed/blob/master/src/client/app/%2Babout/components/about.component.ts

fix home component paths

---

gulpfile.ts
tools/tasks/seed/build.js.dev.ts

// cc @ludohenin @d3viant0ne @totev

perf(build): remove linting and add gulp-cached

---

package.json
src/client/app/+about/components/about.component.spec.ts
src/client/app/+home/components/home.component.spec.ts
src/client/app/components/app.component.spec.ts
src/client/main.ts

I've updated the project to release beta.16 and modified the tests, however it was a little rushed so not 100% they've been updated correctly.

Update to release beta.16

---

.travis.yml
README.md

chore(readme): change node requirements

---

tools/config/seed.config.ts

Simple fix to load package.json's

Fixes json package paths

---

tools/config/seed.config.ts

Changed APP_DEST so its determined by the environment build.

---

README.md

angular/progressive now officially sits at angular/mobile-toolkit

docs(): update angular/progressive => angular/mobile-toolkit

---

package.json

fix: e2e command

---

tools/tasks/project/sample.task.ts
tools/tasks/seed/build.assets.dev.ts
tools/tasks/seed/build.assets.prod.ts
tools/tasks/seed/build.docs.ts
tools/tasks/seed/build.index.prod.ts
tools/tasks/seed/build.js.e2e.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/build.js.test.ts
tools/tasks/seed/build.js.tools.ts
tools/tasks/seed/check.versions.ts
tools/tasks/seed/clean.all.ts
tools/tasks/seed/clean.dev.ts
tools/tasks/seed/clean.prod.ts
tools/tasks/seed/clean.tools.ts
tools/tasks/seed/karma.start.ts
tools/tasks/seed/serve.coverage.ts
tools/tasks/seed/serve.docs.ts
tools/tasks/seed/server.prod.ts
tools/tasks/seed/server.start.ts
tools/tasks/seed/watch.dev.ts
tools/tasks/seed/watch.e2e.ts
tools/tasks/seed/watch.test.ts

Added missing semicolons to tasks.

---

protractor.conf.js

fix(protractor): lost

---

tools/config/project.config.ts
tools/config/seed.config.ts

Hey guys,
as announced beforehand, here is my proposal to add inline documentation for the project.config.ts and seed.config.ts using jsdoc notation (http://usejsdoc.org/). This aims to fix #861.
Greetings
Dope

Document project and seed configuration

---

src/client/app/+about/about.component.ts
src/client/app/+about/index.ts
src/client/app/+home/home.component.ts
src/client/app/+home/index.ts
src/client/app/app.component.ts
src/client/app/main.ts
src/client/app/shared/index.ts
src/client/app/shared/name-list/index.ts
src/client/app/shared/name-list/name-list.service.ts
src/client/app/shared/navbar/index.ts
src/client/app/shared/navbar/navbar.component.ts
src/client/app/shared/toolbar/index.ts
src/client/app/shared/toolbar/toolbar.component.ts

Hey guys,
this is the PR to complete the first task of #867, providing inline documentation for the TypeScript files
within `src/client` using the jsdoc notation. 
Any feedback / change request to this PR is very much welcome :)
Greetings
Dope

Document sources in src/client

---

tools/utils/project.utils.ts
tools/utils/project/sample_util.ts
tools/utils/seed.utils.ts
tools/utils/seed/clean.ts
tools/utils/seed/code_change_tools.ts
tools/utils/seed/server.ts
tools/utils/seed/tasks_tools.ts
tools/utils/seed/template_locals.ts
tools/utils/seed/tsproject.ts
tools/utils/seed/watch.ts

Hey guys,
this is the next PR for adding inline documentation inline documentation for the TypeScript files
within `tools/utils` using the jsdoc notation. (As per task list in #867.)
If you have further change requests, go right ahead an i'll integrate them.
Greetings 
Dope

Document sources in tools/utils

---

tools/config/seed.config.ts

pass at functionality requested at #875

added --b flag to prevent browser from open on serve.dev

---

tools/config/seed.config.ts

With that it's possible to keep different clients in the project

Configurable client folder

---

src/client/app/+home/home.component.html
src/client/app/+home/home.component.spec.ts
src/client/app/app.component.ts
src/client/app/shared/name-list/name-list.service.spec.ts
src/client/app/shared/name-list/name-list.service.ts
src/client/assets/data.json

feat(http): add sample http service calls

---

karma.conf.js
package.json
tools/config/seed.config.ts
typings.json

chore(build): migrate to core-js from es6-shim

---

tools/tasks/seed/build.bundles.app.ts

chore(build): Catch build.bundle.app errors

---

tools/manual_typings/seed/cssnano.d.ts
tools/tasks/seed/build.html_css.ts

This was breaking z-indexes in my files when using the seed.

Only use safe cssnano transformations (stop breaking z-indexes)

---

tools/config/seed.config.ts

perf(initial-load): load bundles instead of lib files separately

---

karma.conf.js
package.json
tools/config/seed.config.ts

confused :point_down:
https://github.com/mgechev/angular2-seed/blob/576e705e39429a9000c37f6af5a4029e71a76a8d/tools/tasks/seed/build.bundles.ts#L38

chore: core-js instead of reflect-metadata

---

tools/tasks/seed/build.html_css.ts

- Compile css stylesheets listed in global configuration #971 
- Changes are non-breaking
- Refactored stylesheet processing functions
- Reordered import statement variables alphabetically
- Updated documentation

Hotfix for issue #971

---

src/client/app/+about/about.component.e2e-spec.ts
tools/tasks/seed/e2e.ts

hotfix(e2e): fix travis broken tests

---

tools/config/seed.config.ts
tools/tasks/seed/build.js.prod.ts

Issue #1036 
* Remove inline-template support for build.js.prod.

Issue #1036

---

tools/config/seed.config.ts

* fixed typo in env property for seed.config.

Typo in ENV annotation about flag.

---

tools/README.md

Fixed a typo

---

src/client/app/+home/home.component.html
src/client/app/+home/home.component.ts
src/client/app/shared/name-list/name-list.service.ts

fixes issue where empty data.json will trigger infinite http requests

move names array to home.component

---

package.json

package.json dependencies update

---

package.json
tools/tasks/seed/build.html_css.ts

fix(build.html_css): handle postcss errors

---

README.md

Please consider adding an example of a game engine (Phaser 2 in this case) integration on your README file.
The modifications to your seed can be seen in [this PR](https://github.com/tiagomapmarques/angular2-seed-phaser/pull/1). Note that the diff is being done against your '2.0.0-rc.3' tag, not the master branch.
I have linted, added/updated specs (and e2e specs). Please feel free to comment on my work. It would be much appreciated.

Example of integration with Phaser2

---

README.md

* add readme link to integration with express js.

Add link to integration with express

---

tools/config/seed.config.ts

* hotfix for production sub-path

Issue #1164 Route with parameters and sub routes fail in production

---

tools/utils/seed/tsproject.ts

fix(makeTsProject): use proper tsconfig.json file

---

README.md

Update the directory structure section in the README.md.

docs(readme): update directory structure

---

src/client/testing/router/mock-location-strategy.ts
src/client/testing/router/router-testing-providers.ts

Apply the rules from the [styleguide](https://angular.io/docs/ts/latest/guide/style-guide.html)
to the source files in `/src/testing`.

style(testing): apply styleguide rules

---

src/client/app/+about/about.component.html

Just a fix for a tiny typo... the paragraph in the About component HTML was not closed properly.

Change <p> to closing tag in About component

---

tools/config/seed.config.ts
tools/tasks/seed/build.js.dev.ts

fix(build.dev): set proper sourceRoot

---

README.md

Updating the README File with the new Environment configuration

Update README.md About Environment configuration

---

tools/tasks/seed/build.bundles.app.ts

Minor tslint bugfix

---

src/client/app/+home/home.component.spec.ts
src/client/app/app.component.spec.ts

At app.component.spec.ts. the indexOf method was removed due it will return -1 when the string does not exist, however -1 is a truethy value.

Updating test to RC5. TestComponentBuilder was removed

---

gulpfile.ts

fix tslint issue

---

src/client/index.html

Fixes https://github.com/mgechev/angular2-seed/issues/1295

Fixed system-config.js import link to include APP_BASE

---

tools/config/seed.config.ts
tools/tasks/seed/build.index.dev.ts

fix for rendering css file in original commit related to #1269, moving rewrite rules to inline of PLUGIN_CONFIGS, mapping /dist/dev/css/ to /css/ in index.html for consistency.

Additional fix for #1269. Also mapping /dist/dev/css/ to /css/ in index.html

---

src/client/tsconfig.json
tools/tasks/seed/compile.ahead.prod.ts

fix(tools): remove typings.d.ts from project tsconfig

---

package.json

Fix https://github.com/angular/zone.js/issues/436

Update zone js to fix error in edge

---

src/client/app/shared/name-list/name-list.service.spec.ts
tools/tasks/seed/build.assets.prod.ts

I am using the tslint rule no-shadowed-variable additionally in my project and had to fix two issues in the code base. I thought maybe you want to apply those fixes as well

fixed variable shadowing issues

---

README.md

chore: advanced seed rename update

---

tools/tasks/seed/copy.prod.ts

See https://github.com/mgechev/angular-seed/issues/1513

Remove redundant steps

---

.travis.yml

ci: update

---

gulpfile.ts
package.json

feature(tools): serve.prod.exp Fix #1559

---

karma.conf.js
package.json
tools/config/seed.config.ts

@netstart here's the `intl` shim.

fix(seed): add intl polyfills

---

package.json
tools/config/seed.config.ts
tools/tasks/seed/clean.coverage.ts
tools/tasks/seed/karma.run.ts
tools/tasks/seed/karma.run.with_coverage.ts
tools/tasks/seed/serve.coverage.watch.ts
tools/utils/seed/server.ts

Added COVERAGE_TS_DIR to config and karma-remap-istanbul to default karma reporters config

---

package.json
tools/config/seed.config.ts
tools/tasks/css_task.ts
tools/tasks/seed/build.html_css.ts

https://github.com/mgechev/angular-seed/issues/1452

feat(sass improvement)

---

.vscode/launch.json

Added sourceMapPathOverrides in  "Attach to Chrome, with sourcemaps" task and add preLaunchTask to build before launch.

sourceMapPathOverrides + added preLaunchTask

---

tools/config/seed.config.ts

This resolves https://github.com/mgechev/angular-seed/issues/1619

- Fix resolution of external dependencies during production build on Linux

---

.docker/angular-seed.development.dockerfile
.docker/angular-seed.production.dockerfile
.docker/nginx.conf
README.md
docker-compose.production.yml
docker-compose.yml

Implement a docker production container, which serves the static files
built from running `npm run build.prod` in a nginx web server.
Fixes #1602

feat(docker): provide docker nginx prod

---

src/client/app/about/about-routing.module.ts
src/client/app/about/about.module.ts
src/client/app/about/about.routes.ts
src/client/app/about/index.ts
src/client/app/app-routing.module.ts
src/client/app/app.module.ts
src/client/app/app.routes.ts
src/client/app/home/home-routing.module.ts
src/client/app/home/home.module.ts
src/client/app/home/home.routes.ts
src/client/app/home/index.ts

- removed .routes.ts files and replaced them with -routing.module.ts files (corresponding to [Angular Style Guide 02-12](https://angular.io/styleguide#02-12))
- removed extra blank line between Decoration and class

routing corresponding to STYLE 02-12

---

src/client/app/about/about.component.spec.ts
tools/config/seed.tslint.json
tools/tasks/seed/check.versions.ts
tools/tasks/seed/generate.manifest.ts

Indentation rule was incorrect and not checking on spaces. [TSLint - indentation](https://palantir.github.io/tslint/rules/indent/)
Updated the rule and replaced some tabs to spaces.

Tslint indent with spaces

---

tools/tasks/seed/build.index.prod.ts

I enabled the tslint rule "whitespace > check-operator" in my project and one error popped up. Would be nice if you could merge it so I do not get a merge conflict every time I am pulling from your repository.

whitespace cleanup

---

package.json

Moving up to version 4.0.14 to avoid broken builds

Fixing issue with protractor, moving up to vrsion 4.0.14

---

tools/tasks/seed/compile.ahead.prod.ts

fix(build): add manual typings for aot

---

tsconfig.json

chore: set proper target of tsconfig.json

---

src/client/app/shared/name-list/name-list.service.ts
src/client/index.html

Fixed all paths to be compatible with a 'production' deployment. This applies to the case where your base url is different than '/'. I've tested this by applying the following line to `project.config.ts` and hosting it accordingly:
```
this.APP_BASE = '/~user/folder/';
```

fix paths production deployment

---

tools/config/project.config.ts
tools/config/seed.config.ts
tools/tasks/seed/build.index.prod.ts
tools/tasks/seed/e2e.ts
tools/utils/seed/server.ts

Fix: issue of not overridable PORT or any other property which is used in other property objects of SeedConfig with ProjectConfig
- renamed CSS_PROD_BUNDLE to CSS_BUNDLE_NAME;
- changed method of adding proxy middleware;

Fix: issue of not overridable PORT or any other property in ProjectConfig

---

src/client/app/home/home.module.ts

Removed the extra CommonModule import which is already being imported by SharedModule. This is very minor but wanted to fix it.

HomeModule imports CommonModule 2 times

---

tools/config/seed.tasks.json

This small fix will fix issue #1821

fix test.watch error

---

tools/config/seed.config.ts
tools/tasks/seed/build.index.dev.ts
tools/tasks/seed/build.index.prod.ts

feat(tools): allow setting custom query string

---

package.json
yarn.lock

fix(tools): new version of rollup cjs

---

tools/config/project.config.ts
tools/env/base.ts
tools/env/dev.ts
tools/env/prod.ts

- fix typo
- use export default

Use export default

---

tools/config/project.config.ts
tools/env/base.ts
tools/env/dev.ts
tools/env/prod.ts

Reverts mgechev/angular-seed#1866

Revert "Use export default"

---

tools/README.md
tools/tasks/seed/clean.tools.ts

Just a small fix on a mispelled word ^^

Fix mispelling

---

tools/config/project.config.ts

added `'/api',` route to proxy example comment #1883

---

package.json

Version 1 adds cool new features.

Move to compodoc v1

---

tools/tasks/seed/build.html_css.ts

Reverts mgechev/angular-seed#1920

fix(tools): cache SCSS files in prod & dev build

---

tools/tasks/seed/build.js.prod.rollup.aot.ts
tools/tasks/seed/transpile.bundles.rollup.aot.ts

We stumbled upon this error too today, thanks to @rbr82 for this finding.
Fixes #1300

Fixes lexical scope issues on error, referenced in issue #1300

---

src/client/app/shared/name-list/index.ts

obsolete file
rebased and tests passing
[https://github.com/madcalfus/angular-seed/pull/1](https://github.com/madcalfus/angular-seed/pull/1)

chore: remove name-list index.ts

---

karma.conf.js
package.json
src/client/app/system-config.ts
test-config.js
tools/config/seed.config.ts
yarn.lock

build: update to system 0.20

---

package.json

Call compodoc binary directly without node

---

tools/config/seed.config.ts

mistake in the comment of seed.config.ts so I pull request.

corrected LOCALE_DEST comment in seed.config.ts file

---

package.json
tools/config/seed.config.ts
tools/tasks/seed/build.bundle.rxjs.ts
yarn.lock

Reverts mgechev/angular-seed#1985

Revert "Postinstall script update"

---

tools/tasks/seed/build.js.prod.rollup.aot.ts

fix: Multi app rollup prod build

---

tools/tasks/seed/build.html_css.ts
tools/utils/seed/server.ts

Fix spelling error and remove duplicates

Fix spelling error and remove duplicates

---

tools/env/env-config.interface.ts
tools/utils/seed/template_locals.ts

Expose package version to the application

add version to envConfig

---

package.json
tools/debug.ts
tools/tasks/seed/build.tools.ts
tools/tasks/seed/compile.ahead.prod.ts
yarn.lock

Fix typing errors

---

tools/config/seed.config.ts
tools/tasks/seed/build.index.dev.ts
tools/tasks/seed/build.index.prod.ts
tools/tasks/seed/build.js.dev.ts
tools/tasks/seed/build.js.e2e.ts
tools/tasks/seed/build.js.prod.aot.ts
tools/tasks/seed/build.js.prod.rollup.aot.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/transpile.bundles.rollup.aot.ts

Fix #2062
You can now set custom interpolation regex.

Allow custom template interpolation chars

---

tools/utils/seed/template_locals.ts

Correct capitalization of the version variable

fix version capitalization

---

src/client/app/i18n.providers.ts

When you uncomment the file, it doesn't pass the linter. I fixed it and also variables which are never changed are now using 'const' instead of 'let'.

I18n.providers to pass linter

---

tools/config/seed.config.ts

Fixed "SyntaxError: Unexpected token <" issue [#2084](https://github.com/mgechev/angular-seed/issues/2084) by adding the tslib into additionalPackages inside "tools/config/seed.config.ts" .

Fixed HttpClientModule import issue #2084

---

package.json
tools/tasks/seed/build.bundle.rxjs.ts
yarn.lock

chore: fix rxjs System bundling

---

karma.conf.js
tools/config/seed.config.ts

Add HttpClientTestingModule to seed.config.ts

---

README.md

Hi @mgechev 👋 
Small adjustment to the README to not mislead 👍 
Please take note of this [notice](https://github.com/NathanWalker/angular-seed-advanced/issues/474).
Hope to see ya at your SF Meetup sometime!

docs: readme note about advanced seed option

---

package-lock.json
package.json
yarn.lock

Update:
* Add support of `Angular Language Service`.
More details: https://angular.io/guide/language-service#angular-language-service

Add support of `Angular Language Service`

---

src/client/app/app.module.ts
src/client/app/shared/name-list/name-list.service.spec.ts
src/client/app/shared/name-list/name-list.service.ts

Update:
* Http client update.
* Unit tests with http client update.

Http Client update with unit tests

---

tools/config/seed.config.ts

chore: fix rxjs system config

---

tools/tasks/seed/build.html_css.ts
tools/tasks/seed/build.js.prod.aot.ts
tools/tasks/seed/build.js.prod.rollup.aot.ts
tools/tasks/seed/build.js.prod.ts
tools/tasks/seed/compile.ahead.prod.ts
tools/tasks/seed/i18n.build.ts
tools/tasks/seed/karma.run.without_coverage.ts
tools/tasks/seed/start.deving.ts
tools/tasks/seed/test.watch.ts
tools/tasks/seed/transpile.bundles.rollup.aot.ts
tools/tasks/task.ts
tools/utils/seed/clean.ts

Update:
* Small code cleanup.
* Few annotations update.

Small cleanup

---

tools/config/project.config.ts

Update:
* Small variable hotfix.

Small variable hotfix

---

package-lock.json
package.json
tools/tasks/seed/build.bundles.app.rollup.aot.ts
tools/tasks/seed/build.js.prod.aot.ts
tools/tasks/seed/build.js.prod.rollup.aot.ts
tools/tasks/seed/minify.bundles.ts
tools/utils/seed.utils.ts
tools/utils/seed/build_optimizer.ts
yarn.lock

feat: introduce bundle optimizer

---

package.json
tools/config/seed.config.ts

drop deprecated angular http dependency

---

package.json
tools/tasks/seed/build.bundle.rxjs.ts
yarn.lock

Update to RxJS@5.5.3

---

karma.conf.js
package.json
test-config.js
tools/config/seed.config.interfaces.ts
tools/config/seed.config.ts
tools/tasks/seed/bundle.rxjs.ts

Added task to bundle rxjs for less request.
currently there are 271 request when you npm start or start the app.
with this bundle it would be 55 request only.

add bundle rxjs for less request

---

.travis.yml
appveyor.yml
package-lock.json
package.json
yarn.lock

We should not forget to remove `resolutions` block from `package.json` once Angular updates to TypeScript >2.8.

add resolutions field to package.json
